export const AUTH_FETCH = 'AUTH_FETCH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const STOCKS_FETCH = 'STOCKS_FETCH'
export const STOCKS_SUCCESS = 'STOCKS_SUCCESS'
export const STOCKS_FAILURE = 'STOCKS_FAILURE'

export const COMPANY_FETCH = 'COMPANY_FETCH'
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS'
export const COMPANY_FAILURE = 'COMPANY_FAILURE'

export const SETTING_FETCH = 'SETTING_FETCH'
export const SETTING_SUCCESS = 'SETTING_SUCCESS'
export const SETTING_FAILURE = 'SETTING_FAILURE'